# Generated by Django 5.0.2 on 2024-04-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhtor',
            new_name='author',
        ),
    ]
